### ISSUE TITLE
Some cterm colors differ from gui colors

### ISSUE THREAD

**Issue by ghost** [quantum-omega/vim-burnttoast256#1]
For the vast majority of highlight/syntax groups, the RGB values for the cterm arguments agree with the gui arguments.  However, that is not true for the following: CursorLineNr. IncSearch, LineNr, TabLine, TabLineFill, and Special.  

As an example, ctermfg for Special is set to 132, equivalent to #af5f87 but guifg is #d78787.  

This is not a complaint, just an observation.  I like and use this colorscheme.

**Comment by quantum-omega** [comment]
Thanks. I will take a look at it. I barely ever use the GUI version so I might have missed a few of them.

**Comment by ghost** [comment]
You are welcome.  I'm the opposite- I hardly ever use the terminal settings.
I only noticed this because I've been using an older version and saw your
latest commit.

**Comment by quantum-omega** [comment]
Version 1.4 should fix the inconsistencies and I made a script which should help me detect them in the future.
